#!/bin/bash

#
#   A haiku to openssl:
#
#       openssl
#       a black crane over the lake
#       may you rot in hell
#

. /etc/d3ck/config.sh

if [ "X$1" = "X" ]; then
    echo Usage: $0 name
    exit 1
else
    clientname="$1"
fi

vpn_home="/etc/d3ck/d3cks/vpn_client"
vtarget="$vpn_home/$clientname"

cd /etc/d3ck/f-u-openssl

. d3ck-vars

# client
KEY_CN=$(dd if=/dev/urandom bs=16 count=1 2>/dev/null| hexdump |awk '{$1=""; printf("%s", $0)}' | sed 's/ //g')
magic="-subj /C=$KEY_COUNTRY/ST=$KEY_PROVINCE/L=$KEY_CITY/O=$KEY_ORG/CN=$KEY_CN"

echo COMMON NAME IS: "$KEY_CN"

echo $vtarget

openssl req -nodes -batch -new -newkey rsa:$KEY_SIZE -keyout "$vtarget.key" -out "$vtarget.csr" -config stupid.conf
openssl ca -cert ca.crt $magic -batch -keyfile ca.key -days $d3ck_vpn_life_tmp -out "$vtarget.crt" -in "$vtarget.csr" -config stupid.conf

cd $vpn_home

# hmmm... id?
# openssl x509 -noout -fingerprint -in $vpn_home/$clientname.crt | awk -F= '{print $2}' | sed 's/://g' | tee -a $vpn_home/$clientname.pid

# get IP's of server
remote=$(ifconfig | awk '{if (n) { all[dev] = substr($2, match($2, ":") + 1); n = 0 }} {if (match($0, "^[^ \t]") && $1 != "lo" && !match($1, "^tun")) { n = 1; dev = $1; all[dev]="" }} END { for (i in all) print "remote", all[i]}'| sed 's/,]$/]/')

echo remote: $remote

echo
echo generating p12:
echo
echo "    $vtarget.p12"
echo
echo You will need to securely mail or get to your client and install it.
echo "The password (required by Apple's IOS, at least) is 'D3CK' (without quotes!)"
echo

openssl pkcs12 -password pass:D3CK -export -in $vtarget.crt -inkey $vtarget.key -certfile $hell/ca.crt -name $clientname -out $vtarget.p12

echo
echo now generating openvpn configuration file
echo
echo "    $vtarget.ovpn"
echo
echo You will need to securely transfer it to your client and install it as well
echo

(cat << EOV
#
# OpenVPN client conf, generated by D3CK
#
client
dev tun

proto $d3ck_vpn_proto
port  $d3ck_vpn_port
$remote

cipher $d3ck_cipher
auth $d3ck_auth

# seems recommended
tun-mtu  1500

comp-lzo    
nobind    
verb    5

# for up/down scripts
script-security 2

remote-cert-tls server

single-session

key-direction 1

EOV

echo "<ca>"
cat /etc/d3ck/d3cks/D3CK/ca.crt
echo "</ca>"
echo
echo "<cert>"
cat $vtarget.crt
echo "</cert>"
echo
echo "<key>"
cat $vtarget.key
echo "</key>"
echo
echo "<tls-auth>"
cat /etc/d3ck/d3cks/D3CK/ta.key
echo "</tls-auth>"
) > $vtarget.ovpn


echo
echo '**** WARNING!  On IOS Multiple "remote" entries seems to not work ;('
echo

